<?php

namespace TDB\Empresa1Bundle\Repository;

/**
 * Dim_ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dim_ItemRepository extends \Doctrine\ORM\EntityRepository
{
}
