<?php

namespace TDB\Empresa1Bundle\Repository;

/**
 * Fact_MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Fact_MovimientosRepository extends \Doctrine\ORM\EntityRepository
{
    
}
