imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@TDBEmpresa1Bundle/Resources/config/services.yml" }
    - { resource: "@TDBAdministracionBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en


framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        #default_connection: default
        connections:
          #default:
              #driver:   "pdo_sqlsrv"
              #host:     "%database_host%"
              #port:     "%database_port%"
              #dbname:   "%database_name%"
              #user:     "%database_user%"
              #password: "%database_password%"
              #charset:  UTF8
          administracion:
              driver:   "pdo_sqlsrv"
              host:     '%database_host%'
              port:     '%database_port%'
              dbname:   '%database_name2%'
              user:     '%database_user%'
              password: '%database_password%'
              charset:  UTF8
          empresa1:
              driver:   "pdo_sqlsrv"
              host:     '%database_host%'
              port:     '%database_port%'
              dbname:   '%database_name3%'
              user:     '%database_user%'
              password: '%database_password%'
              charset:  UTF8
    orm:
        #default_entity_manager: default
        entity_managers:
            #default:
            #    connection: default
            #    mappings:
            #        AppBundle:  ~
            administracion:
                connection: administracion
                mappings:
                    TDBAdministracionBundle: ~
            empresa1:
                connection: empresa1
                mappings:
                    TDBEmpresa1Bundle: ~
    #orm:
        #auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# app/config/config.yml
genemu_form:
    select2: ~

# KNP PAGINATOR
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template